### ISSUE TITLE
How to use my own dataset for model training??

### ISSUE THREAD

**Issue by lanyao-wang** [imJouch/crack-detection#2]
hello jouch,
I'd like to know how to make a dataset that conforms to the yolov5 model?
And how to use my own dataset for training?

For example, 
I saw that there are data sets stored in **paper_data** folder, how can I generate the txt files of the original image and labels?

**Comment by imJouch** [comment]
您好，您的邮件已经收到。

**Comment by imJouch** [comment]
split_train_val.py, the detail refers https://blog.csdn.net/qq_36756866/article/details/109111065
